<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ValidatedWorld.Core\ValidatedWorld.Core.csproj" />
    <ProjectReference Include="..\ValidatedWorld.Validation\ValidatedWorld.Validation.csproj" />
  </ItemGroup>

</Project>
